services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medods_app
    ports:
      - "${PORT}:8080"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_SSLMODE: ${DB_SSLMODE}
      JWT_SECRET: ${JWT_SECRET}
      WEBHOOK_URL: ${WEBHOOK_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: medods_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./docs:/docs

volumes:
  pg_data:
